_itemsSource['weapons_custom'] = {
	{
		name = 'WEAPON_GLOCK19X2',
		label = 'PD Block',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 17,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK19X',
		label = '9mm 19x',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 17,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK19',
		label = 'GRP Auto 19',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK40',
		label = 'GRP Auto 40',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK40S',
		label = 'GRP Auto 40s',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_DDM4V5',
		label = 'DDM4V5',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PD509',
		label = 'PD 509',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_APS',
		label = 'Stechkin APS',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PPK',
		label = 'PPK',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PITVIPER',
		label = 'JW4 PIT Vper',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_BARP',
		label = 'banshee ARP-9',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_RDP',
		label = 'Hellcat RDP',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_LOK',
		label = 'M-Lok AR 15',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PLR',
		label = 'PLR-16',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_XDS9',
		label = 'XDS9',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PPS',
		label = 'PPS',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_XDME',
		label = 'XDM Elite',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_SP',
		label = 'NF-15',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK17S',
		label = 'GRP auto 17s',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	-- {
	-- 	name = 'WEAPON_GLOCK18C', -- broken model
	-- 	label = 'GRP auto 18c',
	-- 	ammoType = 'AMMO_PISTOL',
	-- 	requiresLicense = true,
	-- 	price = 200,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 42),
	-- 	type = 2,
	-- 	rarity = 1,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 10,
	-- 	gun = true,
	-- },
	{
		name = 'WEAPON_GLOCK19S',
		label = 'GRP auto 19s',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_ARPISTOL',
		label = 'Tatuc ARP 9mm',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK26S',
		label = 'GRP Auto 26s',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GRENADES',
		label = 'Grenade Sniper',
		ammoType = 'AMMO_GRENADELAUNCHER',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_M32S',
		label = 'M32 Smoke GL',
		ammoType = 'AMMO_GRENADELAUNCHER_SMOKE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_MICRODRACO',
		label = 'Micro Draco',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_RUGER57',
		label = 'Luger 57',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_MK18',
		label = 'MK18 MOD 1',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_680',
		label = 'Model 680',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_ZIPTIE',
		label = 'Zip Tie M4A1',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},

	{
		name = 'WEAPON_BMARP',
		label = 'Mafia ARP',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_BMGLOCK',
		label = 'GRP Mafia',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_BLOODSARP',
		label = 'Bloods ARP',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_BLOODSGLOCK',
		label = 'GRP Bloods Blizzy',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_CARTELARP',
		label = 'Cartel ARP',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_CARTELGLOCK',
		label = 'GRP Cartel',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_CRIPSARP',
		label = 'Crips ARP',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_CRIPSGLOCK',
		label = 'GRP Crips',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_FAMILIASARP',
		label = 'Familias ARP',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_FAMILIASGLOCK',
		label = 'GRP Familias',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
}
