_itemsSource['dangerous'] = {
    {
		name = "car_bomb",
		label = "Car Bomb",
		price = 1500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5.0,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 21),
	},
	{
		name = "catalytic_converter",
		label = "Catalytic Converter",
		description = "Potentially Stolen",
		price = 2450,
		isUsable = false,
		isRemoved = false,
		isStackable = 10,
		type = 4,
		rarity = 4,
		closeUi = false,
		metalic = false,
		weight = 25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 10),
	},
	{
		name = "blowtorch",
		label = "Blowtorch",
		description = "Tool for cutting catalytic converters",
		price = 500,
		isUsable = false,
		isRemoved = false,
		isStackable = 5,
		type = 3,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 25,
	},
	{
		name = "markedrolls",
		label = "Marked Rolls",
		description = "Potentially Stolen",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 6,
		rarity = 3,
		closeUi = false,
		metalic = false,
		weight = 0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 10),
	},
	-- Crafting Benches
	{
		name = "weap_bench",
		label = "Weapons Bench",
		description = "A portable weapons crafting bench",
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		isDestroyed = false,
	},
	{
		name = "misc_bench",
		label = "Misc Bench",
		description = "A portable miscellaneous crafting bench",
		price = 3000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 20,
		isDestroyed = false,
	},
	{
		name = "pubcraft_bench",
		label = "Public Crafting Bench",
		description = "A portable public crafting bench",
		price = 4000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 20,
		isDestroyed = false,
	},
	-- Crafting Blueprints
	{
		name = "blueprint_molotov",
		label = "Molotov Blueprint",
		description = "Blueprints for crafting a Molotov",
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
	},
	{
		name = "blueprint_grip",
		label = "Weapon Grip Blueprint",
		description = "Blueprints for crafting a Weapon Grip",
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
	},
	{
		name = "blueprint_suppressor",
		label = "Weapon Suppressor Blueprint",
		description = "Blueprints for crafting a Weapon Suppressor",
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
	},
	{
		name = "blueprint_extendedclip",
		label = "Extended Clip Blueprint",
		description = "Blueprints for crafting an Extended Clip",
		price = 350,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
	},
	{
		name = "blueprint_scope",
		label = "Weapon Holoscope Blueprint",
		description = "Blueprints for crafting a Holographic Scope",
		price = 450,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
	},
}