_itemsSource["labor"] = {
	{
		name = "unknown_ore",
		label = "Unknown Ore",
		price = 0,
		isUsable = false,
		isStackable = 15,
		type = 7,
		rarity = 5,
		closeUi = false,
		metalic = false,
		weight = 3.0,
	},
	{
		name = "packaged_parts",
		label = "Packaged Parts",
		price = 0,
		isUsable = false,
		isStackable = 1,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 4.0,
	},
	{
		name = "hunting_bait",
		label = "Hunting Bait",
		price = 10,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "deer_bait",
		label = "Deer Bait",
		iconOverride = "hunting_bait",
		price = 20,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "boar_bait",
		label = "Boar Bait",
		iconOverride = "hunting_bait",
		price = 20,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "pig_bait",
		label = "Pig Bait",
		iconOverride = "hunting_bait",
		price = 20,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "chicken_bait",
		label = "Chicken Bait",
		iconOverride = "hunting_bait",
		price = 20,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "rabbit_bait",
		label = "Rabbit Bait",
		iconOverride = "hunting_bait",
		price = 20,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "exotic_bait",
		label = "Exotic Bait",
		iconOverride = "hunting_bait",
		price = 1000,
		isUsable = true,
		isStackable = 20,
		type = 7,
		rarity = 5,
		closeUi = true,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "oaklog",
		label = "Oak Log",
		price = 0,
		isUsable = false,
		isStackable = 50,
		type = 7,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 5.0,
	},
	{
		name = "woodplank",
		label = "Wood Plank",
		price = 0,
		isUsable = false,
		isStackable = 50,
		type = 7,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 2.0,
	},
	{
		name = "WEAPON_PRESSURE1",
		label = "Pressure Washer",
		weapon = "WEAPON_PRESSURE1",	
		ammoType = "NONE",
		requiresLicense = false,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 30),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
		noSerial = true,
	},
}
