_itemsSource['gangs'] = {
	{
		name = "glaptop",
		label = "Gangs Laptop",
		price = 1250,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 999,
		rarity = 4,
		closeUi = true,
		metalic = true,
		state = "GLAPTOP",
        iconOverride = "laptop",
		weight = 4,
		durability = (60 * 60 * 24 * 30),
	},

    {
		name = "scrubbingcloth",
		label = "Scrubbing Cloth",
		price = 1250,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 999,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 4,
		durability = (60 * 60 * 24 * 30),
	},

    {
        name = "spray_dev",
        label = "Dev Gang Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_KR",
        label = "21 Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_los_aztecas",
        label = "Los Aztecas Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_flying_dragons",
        label = "Flying Dragons Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_kings",
        label = "Kings Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_dark_wolves",
        label = "Dark Wolves Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_death_sinners",
        label = "Death Sinners Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_white_widow",
        label = "White Widow Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_ballas",
        label = "Ballas Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_wutang",
        label = "Wu-Tang Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_vatoslocos",
        label = "Vatos Locos Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_bumpergang",
        label = "BumperGang Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_sopranos",
        label = "Sopranos Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_s2n",
        label = "Second2None Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_fts",
        label = "Fock The System Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_tffc",
        label = "Thieves & Crooks Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },
    
    {
        name = "spray_joker_cartel",
        label = "Joker Cartel Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    {
        name = "spray_mygang",
        label = "The Bloods Spray",
        description = "Lets imagine something cool.",
        price = 7500,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 999,
        rarity = 4,
        closeUi = true,
        metalic = false,
        weight = 0.5,
        durability = (60 * 60 * 24 * 14),
    },

    -- Gangsystem Items (from ox_inventory_items.lua)
    {
        name = "pure_tablet",
        label = "Gang Tablet",
        description = "A tablet for managing your gang",
        price = 0,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = false,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        iconOverride = "tablet",
        weight = 1.0,
    },
    {
        name = "bp_bench",
        label = "Blueprint Bench",
        description = "A Blueprint Bench that generates Blueprints",
        price = 0,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = false,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 10.0,
    },
    {
        name = "spraycan",
        label = "Spray Can",
        description = "A Spray Can for creating gang tags",
        price = 0,
        isUsable = true,
        isRemoved = false,
        isStackable = true,
        isDestroyed = false,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = false,
        weight = 0.5,
    },
    {
        name = "paintstriper",
        label = "Paint Striper",
        description = "For stripping paint from gang tags",
        price = 0,
        isUsable = true,
        isRemoved = false,
        isStackable = true,
        isDestroyed = false,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = false,
        weight = 0.5,
    },
    {
        name = "boogieboard",
        label = "Boogie Board",
        description = "A Boogie Board",
        price = 0,
        isUsable = false,
        isRemoved = false,
        isStackable = false,
        isDestroyed = false,
        type = 6,
        rarity = 1,
        closeUi = false,
        metalic = false,
        weight = 2.0,
    },
    {
        name = "brandybottle",
        label = "Brandy Bottle",
        description = "A Bottle of Brandy",
        price = 0,
        isUsable = false,
        isRemoved = false,
        isStackable = false,
        isDestroyed = false,
        type = 1,
        rarity = 1,
        closeUi = false,
        metalic = false,
        weight = 0.5,
    },
    {
        name = "dufflebag",
        label = "Duffle Bag",
        description = "A Duffle Bag",
        price = 0,
        isUsable = false,
        isRemoved = false,
        isStackable = false,
        isDestroyed = false,
        type = 10,
        rarity = 1,
        closeUi = false,
        metalic = false,
        weight = 1.0,
    },
    {
        name = "golfclub",
        label = "Golf Club",
        description = "A Golf Club",
        price = 0,
        isUsable = false,
        isRemoved = false,
        isStackable = true,
        isDestroyed = false,
        type = 6,
        rarity = 1,
        closeUi = false,
        metalic = false,
        weight = 1.0,
    },
    {
        name = "wateringcan",
        label = "Watering Can",
        description = "A Watering Can",
        price = 0,
        isUsable = false,
        isRemoved = false,
        isStackable = true,
        isDestroyed = false,
        type = 3,
        rarity = 1,
        closeUi = false,
        metalic = false,
        weight = 0.5,
    },

}